jobs:
  # Example job that runs end-to-end tests using Cypress test runner
  #   https://www.cypress.io/

  # Job names can contain alphanumeric characters and '_', cannot start with a number
  - job: Cypress_e2e_tests
    pool: laptop
    steps:

      - script: npm ci
        displayName: 'Install NPM dependencies'

      - script: npm run cy:verify
        displayName: 'Cypress verify'

      # The next command starts the server and runs Cypress end-to-end tests against it.
      - script: npm run cypress:run
        displayName: 'Run Cypress tests locally'
